# Generated by Django 5.0.1 on 2025-10-04 13:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('es_recurrente', models.BooleanField(default=False, help_text='Indica si es un ingreso recurrente mensual')),
                ('activa', models.BooleanField(default=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ingreso', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Categoría de Ingreso',
                'verbose_name_plural': 'Categorías de Ingreso',
                'ordering': ['iglesia', 'codigo'],
                'unique_together': {('iglesia', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('es_fijo_mensual', models.BooleanField(default=False, help_text='Indica si es un egreso fijo mensual')),
                ('presupuesto_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto mensual asignado para esta categoría', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activa', models.BooleanField(default=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_egreso', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Categoría de Egreso',
                'verbose_name_plural': 'Categorías de Egreso',
                'ordering': ['iglesia', 'codigo'],
                'unique_together': {('iglesia', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('TESORERO', 'Tesorero'), ('PASTOR', 'Pastor'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=20)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['iglesia', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprobante_nro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('categoria_egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.categoriaegreso')),
                ('categoria_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.categoriaingreso')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SaldoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_mes', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_mensuales', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Saldo Mensual',
                'verbose_name_plural': 'Saldos Mensuales',
                'ordering': ['-año_mes'],
                'unique_together': {('iglesia', 'año_mes')},
            },
        ),
    ]
