# Generated by Django 5.0.1 on 2025-10-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_iglesia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
