# Generated by Django 5.0.1 on 2025-10-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimiento_anulado_movimiento_anulado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('rol', models.CharField(choices=[('TESORERO', 'Tesorero'), ('PASTOR', 'Pastor'), ('COLABORADOR', 'Colaborador')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.IntegerField(default=1)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_generados', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_invitacion', to='core.iglesia')),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_usado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Invitación',
                'verbose_name_plural': 'Códigos de Invitación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
