# Generated by Django 5.0.1 on 2025-10-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_codigoinvitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaegreso',
            name='es_fijo_mensual',
        ),
        migrations.RemoveField(
            model_name='categoriaingreso',
            name='es_recurrente',
        ),
    ]
