# Generated by Django 5.0.1 on 2025-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_categoriaegreso_es_fijo_mensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iglesia',
            name='telefono',
        ),
        migrations.AddField(
            model_name='iglesia',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular con WhatsApp', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
