# Generated by Django 5.0.1 on 2025-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_iglesia_telefono_iglesia_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que aceptó los términos', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='terminos_aceptados',
            field=models.BooleanField(default=False, help_text='Indica si el usuario aceptó los términos y condiciones'),
        ),
    ]
