# Generated by Django 5.0.1 on 2025-11-24 20:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_fecha_aceptacion_terminos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoinvitacion',
            name='rol',
            field=models.CharField(choices=[('TESORERO', 'Tesorero'), ('PASTOR', 'Pastor'), ('COLABORADOR', 'Colaborador'), ('TESORERO_CAJA', 'Tesorero de Caja Chica'), ('COLABORADOR_CAJA', 'Colaborador de Caja Chica')], max_length=20),
        ),
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Jóvenes, Caja Ministerio Mujeres', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial con el que se crea la caja', max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_creadas', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_chicas', to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Caja Chica',
                'verbose_name_plural': 'Cajas Chicas',
                'ordering': ['iglesia', 'nombre'],
                'unique_together': {('iglesia', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='codigoinvitacion',
            name='caja_chica',
            field=models.ForeignKey(blank=True, help_text='Si está asignado, el código es para unirse a esta caja chica específica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_invitacion', to='core.cajachica'),
        ),
        migrations.CreateModel(
            name='MovimientoCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprobante_nro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_chica_anulados', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_chica_aprobados', to=settings.AUTH_USER_MODEL)),
                ('caja_chica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.cajachica')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_chica_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja Chica',
                'verbose_name_plural': 'Movimientos de Caja Chica',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('concepto', models.TextField()),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_anuladas', to=settings.AUTH_USER_MODEL)),
                ('caja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='core.cajachica')),
                ('caja_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='core.cajachica')),
                ('movimiento_egreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_egreso', to='core.movimientocajachica')),
                ('movimiento_ingreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_ingreso', to='core.movimientocajachica')),
                ('realizada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre Cajas',
                'verbose_name_plural': 'Transferencias entre Cajas',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_caja', models.CharField(choices=[('TESORERO_CAJA', 'Tesorero de Caja'), ('COLABORADOR_CAJA', 'Colaborador de Caja')], max_length=20)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_caja_realizadas', to=settings.AUTH_USER_MODEL)),
                ('caja_chica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.cajachica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Caja Chica',
                'verbose_name_plural': 'Usuarios de Cajas Chicas',
                'unique_together': {('usuario', 'caja_chica')},
            },
        ),
    ]
