# Generated by Django 5.0.1 on 2025-11-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agregar_cajas_chicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocajachica',
            name='categoria_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_chica', to='core.categoriaegreso'),
        ),
        migrations.AddField(
            model_name='movimientocajachica',
            name='categoria_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_chica', to='core.categoriaingreso'),
        ),
    ]
