# Generated by Django 5.0.1 on 2025-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agregar_categorias_movimientos_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajachica',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso Argentino ($)'), ('USD', 'Dólar Estadounidense (US$)'), ('EUR', 'Euro (€)')], default='ARS', help_text='Moneda de la caja chica. No se puede cambiar una vez creada con movimientos.', max_length=3),
        ),
    ]
